#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : adal
Version  : 1.2.0
Release  : 3
URL      : https://files.pythonhosted.org/packages/0f/ba/07dbea5f63937c4a9a10946107d72b03354f65a51f9e0602314193fc2bae/adal-1.2.0.tar.gz
Source0  : https://files.pythonhosted.org/packages/0f/ba/07dbea5f63937c4a9a10946107d72b03354f65a51f9e0602314193fc2bae/adal-1.2.0.tar.gz
Summary  : The ADAL for Python library makes it easy for python application to authenticate to Azure Active Directory (AAD) in order to access AAD protected web resources.
Group    : Development/Tools
License  : MIT
Requires: adal-python = %{version}-%{release}
Requires: adal-python3 = %{version}-%{release}
Requires: PyJWT
Requires: cryptography
Requires: python-dateutil
Requires: requests
BuildRequires : PyJWT
BuildRequires : buildreq-distutils3
BuildRequires : cryptography
BuildRequires : python-dateutil
BuildRequires : requests

%description
# Microsoft Azure Active Directory Authentication Library (ADAL) for Python
`master` branch    | `dev` branch    | Reference Docs
--------------------|-----------------|---------------
[![Build Status](https://travis-ci.org/AzureAD/azure-activedirectory-library-for-python.svg?branch=master)](https://travis-ci.org/AzureAD/azure-activedirectory-library-for-python) | [![Build Status](https://travis-ci.org/AzureAD/azure-activedirectory-library-for-python.svg?branch=dev)](https://travis-ci.org/AzureAD/azure-activedirectory-library-for-python) | [![Documentation Status](https://readthedocs.org/projects/adal-python/badge/?version=latest)](https://adal-python.readthedocs.io/en/latest/?badge=latest)

%package python
Summary: python components for the adal package.
Group: Default
Requires: adal-python3 = %{version}-%{release}

%description python
python components for the adal package.


%package python3
Summary: python3 components for the adal package.
Group: Default
Requires: python3-core

%description python3
python3 components for the adal package.


%prep
%setup -q -n adal-1.2.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1545534738
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
rm -rf %{buildroot}
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
